# Base configs
baseurl: "https://mh-majumdar.github.io/photography/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by M.H. Majumdar"
subtitle: "Welcome to my photography page,where moments come to life through the lens!"
author: "M.H. Majumdar"
header:
 title: "Photography"
 subtitle: "by M.H. Majumdar"
footer:
 name: "Hey there,I am M.H. Majumdar"
 bio: "I am a programmer,passionate photographer and creative writer.Welcome to my photography page,where moments come to life through the lens!"
 web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://twitter.com/mh_majumdar"
  instagram: "https://www.instagram.com/mh.majumdar_photography/"
  poetfolio: "https://mh-majumdar.github.io/my-portfolio/index.html"
  linkedin: "https://www.linkedin.com/in/hasanmehedi1952/"
  github: "https://github.com/mh-majumdar"
